/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_archivepatcher_generator_hdiff_c2java_hdiff */

#ifndef _Included_com_google_archivepatcher_generator_hdiff_c2java_hdiff
#define _Included_com_google_archivepatcher_generator_hdiff_c2java_hdiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_archivepatcher_generator_hdiff_c2java_hdiff
 * Method:    build_hdiff
 * Signature: (Ljava/lang/Integer;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_google_archivepatcher_generator_hdiff_c2java_1hdiff_build_1hdiff
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
